#!/bin/bash
DIALOG=${DIALOG=dialog}
TMP_FILE=/tmp/gentoo-setup.$$.tmp
TITLE="Alex's Linux Configurator"

# End setup if [ESCAPE] is pressed
exit_on_esc () {
  if (( $1 == 255 )); then
    echo "quitting setup"
    exit 
  fi
}

# Check if a package is installed
install_check () {
  if [[ $(equery -q l $1) =~ . ]]; then 
    echo "1"
  fi
}

# Check that the script is running as the superuser since we need
# permission to edit files in /etc and /usr.
if [ "$EUID" -ne 0 ]; then 
  $DIALOG --backtitle "$TITLE" \
          --title "Superuser not detected" \
          --msgbox "\nPlease run as root." 7 50 
  exit
fi

# Check to see if Gentoo is the OS so we can configure make.conf if so.
# This may be automated in the future.
$DIALOG --backtitle "$TITLE" \
        --title "Distro check" \
        --yesno "\nIs this a Gentoo install?" 7 50
is_gentoo=$?
exit_on_esc $is_gentoo

# If the OS is Gentoo then we need to select one of the supported CPU's
# to specify which make.conf to use.
if (( $is_gentoo == 0 )); then
  while [ -z "$cpu_type" ]; do
    $DIALOG --backtitle "$TITLE" \
            --title "Configuring make.conf" \
            --radiolist "Select your CPU by pressing [SPACE]" 10 50 10 \
                      "1" "i7-2600K" off \
                      "2" "T2300" off \
                      "3" "None of these" on 2> $TMP_FILE
    exit_on_esc $?
	cpu_type=`cat $TMP_FILE`
  done
fi

if [[ $(install_check nano) ]]; then
  echo "success"
  else
  echo "failure"
fi

echo $is_gentoo
echo $cpu_type
